name: ninja-os
description: "Ninja build"
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/varlad/yazi/repo/fedora-%OS_VERSION%/varlad-yazi-fedora-%OS_VERSION%.repo
    install:
      # Development
      - neovim
      - gcc
      - gcc-c++
      - make
      - git
      - git-credential-libsecret
      - lazygit
      - direnv
      - sqlite
      - nodejs
      - python3
      - python3-pip

      # Shell & CLI Utils
      - starship
      - lsd
      - bat
      - fzf
      - fd-find
      - ripgrep
      - yazi
      - btop
      - fastfetch
      - jq
      - rsync
      - ncdu
      - tldr
      - man-db
      - plocate

      # Compression
      - p7zip
      - p7zip-plugins
      - unrar
      - unzip
      - zip
      - zstd
      - lz4

      # System & Hardware
      - distrobox
      - podman
      - podman-compose
      - fuse3
      - wl-clipboard
      - pinentry-qt
      - kitty
      - openssl

      # Gaming Support (Base libs)
      - gamemode
      - mangohud
      - steam-devices

  - type: nvidia
    # This module handles installing the correct kernel drivers and
    # ensuring they are loaded for the RTX 5070 Ti.
    install-open-drivers: true

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: default-flatpaks
    notify: true
    system:
      # Browsers
      - com.google.Chrome
      - org.mozilla.firefox

      # IDEs
      - com.visualstudio.code

      # Gaming
      - com.valvesoftware.Steam
      - com.heroicgameslauncher.hgl
      - net.lutris.Lutris

      # Media & Social
      - org.videolan.VLC
      - com.discordapp.Discord

  - type: script
    scripts:
      - post-install.sh

  - type: signing
    signing_key: /cosign.pub
